language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install --prefer-source --no-interaction --dev

script: phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)